### ISSUE TITLE
not working with spring boot 2.0.2

### ISSUE THREAD

**Issue by peter-ponzel** [tdomzal/junit-docker-rule#42]
hello,
I've been using version 0.3 for quite some time -which worked like a charm-, but after migrating to spring boot 2.0.2 it won't work anymore, see exception:
```
java.lang.NoClassDefFoundError: org/glassfish/hk2/api/MultiException
at pl.domzal.junit.docker.rule.DockerRule.<init>(DockerRule.java:81)
at pl.domzal.junit.docker.rule.DockerRuleBuilder.build(DockerRuleBuilder.java:51)
```
upgrading to version 0.4 didn't fixed that.
have you experienced the same issue?

**Comment by tdomzal** [comment]
Hi, 

I'll take look at it but quick thought...
`junit-docker-rule` does not depend on `org/glassfish` classes but, spotify docker client does.
So I suspect it has something to do with mixing third-party dependencies.
Fixing it without possibility to reproduce it may be hard.

Can you provide smallest possible maven project that will show this problem ?

**Comment by peter-ponzel** [comment]
[demo.zip](https://github.com/tdomzal/junit-docker-rule/files/2079931/demo.zip)
sure, here it is.. I used springs initializr ( https://start.spring.io/ ) and added junit-docker-rule as dependency as well as this piece of code for the test:

@ClassRule
	public static final ExternalResource CONTAINER;

```
	static {
		CONTAINER = DockerRule.builder()
				.imageName("docker.elastic.co/elasticsearch/elasticsearch:6.0.1")
				.expose("9200", "9200")
				.env("discovery.type", "single-node") // run in developer mode
				.env("xpack.security.enabled", "false") // disable security for testing
				.waitFor(WaitFor.httpPing(9200))
				.build();
	}
```

**Comment by peter-ponzel** [comment]
hello, did you managed to figure something out?

**Comment by tdomzal** [comment]
Hi,
It fact I have.

Thanks for mini demo - it gave quick start.
Unforunatelly looks lik problem is introduced by libraries I depend on and only option to fix this is workaround.
This is what I have discovered.

Original error stack trace is:

```
    java.lang.NoClassDefFoundError: org/glassfish/hk2/api/MultiException
        at pl.domzal.junit.docker.rule.DockerRule.<init>(DockerRule.java:81)
        at pl.domzal.junit.docker.rule.DockerRuleBuilder.build(DockerRuleBuilder.java:51)
        ...
    Caused by: java.lang.ClassNotFoundException: org.glassfish.hk2.api.MultiException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 33 more
```
    
Docker spotify client rule depends on uses org.glassfish.hk2.api.MultiException directly and it's not available in classpath.

https://github.com/spotify/docker-client/blob/v8.9.2/src/main/java/com/spotify/docker/client/DefaultDockerClient.java#L180

Current (simplified) dependency tree:
```
    com.example:demo:jar:0.0.1-SNAPSHOT
    \- com.github.tdomzal:junit-docker-rule:jar:0.4:test
       +- com.spotify:docker-client:jar:8.9.2:test
          +- org.glassfish.jersey.core:jersey-client:jar:2.26:test
          |  +- ...
          |  +- org.glassfish.jersey.core:jersey-common:jar:2.26:test
          |  |  \- org.glassfish.hk2:osgi-resource-locator:jar:1.0.1:test
          |  \- org.glassfish.hk2.external:javax.inject:jar:2.5.0-b42:test
          +- org.glassfish.jersey.connectors:jersey-apache-connector:jar:2.22.2:test
          +- org.glassfish.jersey.media:jersey-media-json-jackson:jar:2.26:test
             \- org.glassfish.jersey.ext:jersey-entity-filtering:jar:2.26:test
```

Lets include it:

```
    <dependency>
        <groupId>org.glassfish.hk2</groupId>
        <artifactId>hk2-api</artifactId>
        <version>2.5.0-b42</version>
        <scope>test</scope>
    </dependency>
```

No go :(, error message shows there is something more going on here.

```
    java.lang.IllegalStateException: InjectionManagerFactory not found.
        at org.glassfish.jersey.internal.inject.Injections.lambda$lookupInjectionManagerFactory$0(Injections.java:98)
        at java.util.Optional.orElseThrow(Optional.java:290)
        at org.glassfish.jersey.internal.inject.Injections.lookupInjectionManagerFactory(Injections.java:98)
        at org.glassfish.jersey.internal.inject.Injections.createInjectionManager(Injections.java:68)
        at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:432)
```

Little bit of googling and found out that Jersey is pretty tightly dependent on "HK2 Dependency Injection Kernel" and this error message is related to it's initialization.
But from 2.26 of jersey (this is exact version docker-client uses) they decided to prepare for beaking up that HK2 dependency and made some changes. 
Consequence is to make HK2 still work user has to provide Jersey injection implementation explicitely, see: https://jersey.github.io/release-notes/2.26.html

In fact there is Jersey issue registered that suggest improving this error message:
https://github.com/jersey/jersey/issues/3748

Lets include dependency to higher level library as described in Jersey Release Notes:

```
        <dependency>
            <groupId>org.glassfish.jersey.inject</groupId>
            <artifactId>jersey-hk2</artifactId>
            <version>2.26</version>
            <scope>test</scope>
        </dependency>
```

That gives us, next problem...
Guava missing ?? But it not orginal Guava, it is version repackaged by Jersey....

```
    java.lang.IllegalStateException: com.spotify.docker.client.exceptions.DockerException: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: java.lang.NoClassDefFoundError: jersey/repackaged/com/google/common/util/concurrent/MoreExecutors
        at pl.domzal.junit.docker.rule.DockerRule.<init>(DockerRule.java:90)
        at pl.domzal.junit.docker.rule.DockerRuleBuilder.build(DockerRuleBuilder.java:51)
        at com.example.demo.DemoApplicationTest.contextLoads(DemoApplicationTest.java:18)
        ...
        ...
    Caused by: java.lang.NoClassDefFoundError: jersey/repackaged/com/google/common/util/concurrent/MoreExecutors
        at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:487)
        at org.glassfish.jersey.client.ClientRuntime.lambda$null$3(ClientRuntime.java:187)
        ...
```

Exact same problem like described here:
https://stackoverflow.com/questions/22069316/what-jersey-dependency-to-add-to-avoid-noclassdeffounderror-for-jersey-repackage/22069399
which points to Jersey 2.6 release notes:
https://blog.dejavu.sk/2014/02/21/jersey-2-6-has-been-released-new-and-noteworthy/

Jersey decided to repackage Guava classes used internally to not introduce problems (Guava is quite commonly used library..).
But, for some reason they do not include these repackaged version jersey dependencies.
To be honest I don't get it - what the point in repackaging external libraries to use it internally and not including it in dependencies ?

Anyway, after adding jersey-guava we have now:

```
        <dependency>
            <groupId>org.glassfish.jersey.inject</groupId>
            <artifactId>jersey-hk2</artifactId>
            <version>2.26</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jersey.bundles.repackaged</groupId>
            <artifactId>jersey-guava</artifactId>
            <version>2.25.1</version>
            <scope>test</scope>
        </dependency>
```

And - it's working !
It's ugly (e.g. you should keep version numbers synced with upstream libraries which is problematic) - but working.

Unfortunately I don't see other possibilities for now.

**Comment by peter-ponzel** [comment]
thank you for putting so much effort into this, sadly adding these two dependencies is not enough in my case.. now I'm getting:

```
java.lang.IllegalStateException: {"message":"OCI runtime create failed: container_linux.go:348: starting container process caused \"exec: \\\"eswrapper\\\": executable file not found in $PATH\": unknown"}

	at pl.domzal.junit.docker.rule.DockerRule.before(DockerRule.java:156)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST unix://localhost:80/containers/eab18aff0e3a231d3a98a39d7570000144ebfa22d1a2466b6fcf81427c2105d4/start: 400, body: {"message":"OCI runtime create failed: container_linux.go:348: starting container process caused \"exec: \\\"eswrapper\\\": executable file not found in $PATH\": unknown"}
```
which system are you running and which docker version?
I use Debian 9, Docker version 18.03.1-ce

**Comment by tdomzal** [comment]
This looks like problem INSIDE starting container.
Response to docker API contains come hints:

Caused by: com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST unix://localhost:80/**containers/eab18aff0e3a231d3a98a39d7570000144ebfa22d1a2466b6fcf81427c2105d4/start**: 400, body: {"message":"OCI runtime create failed: container_linux.go:348: starting container process caused \"exec: \\\"**eswrapper**\\\": **executable file not found in $PATH**\": unknown"}

I used something more generic to verify, like:

```
import org.junit.Rule;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import pl.domzal.junit.docker.rule.DockerRule;

@RunWith(SpringRunner.class)
@SpringBootTest
public class DemoApplicationTest {

    @Rule
    public DockerRule container = DockerRule.builder()
                    .imageName("busybox:1.25.1")
                    .cmd("sh", "-c", "echo testing; sleep 1")
                    .build();

    @Test
    public void contextLoads() throws InterruptedException {
        container.waitForExit();
    }
}
```

**Comment by peter-ponzel** [comment]
yes, you're right.. simple images working just fine

**Comment by peter-ponzel** [comment]
I've been looking around on github and it seems to be an issue with docker deamon, see for instance https://github.com/ApolloAuto/apollo/issues/3088
as for the issue itself, I reverted back to 0.3 and added the dependencies, that you mentioned.. now it works :) solved :+1:

**Comment by tdomzal** [comment]
Thanks for closing.
If you find this library useful I'll be grateful for giving it a star ;).
Tomek

**Comment by tdomzal** [comment]
@peter-ponzel 
Your second problem with 0.4:
https://github.com/tdomzal/junit-docker-rule/issues/42#issuecomment-396208387

showed another problem I was unaware of, see:
https://github.com/tdomzal/junit-docker-rule/issues/43

Looks like this is as reason version 0.4 is not working in your case - 0.4.1 is out and you can check if it works for you.

**Comment by peter-ponzel** [comment]
0.4.1 is working like a charm, thank you very much :)
